### ISSUE TITLE
Add option to compile 32 bit native executable

### ISSUE THREAD

**Issue by smlu** [AntelopeIO/cdt#107]
Current `--fnative` compiles code to 64-bit architecture and there is no option to compile the code to 32-bit architecture which is WASM architecture. This can lead to different code execution behavior because the pointer size and some arithmetic types (size_t) don't have the same size between the 2 architectures.

**Comment by stephenpdeos** [comment]
Because we are currently changing how the native testing system will function, we hope this will resolve the challenges you are facing. Reference these proposals for more info https://github.com/eosnetworkfoundation/product/pull/134/files https://github.com/eosnetworkfoundation/product/pull/133/files
