### ISSUE TITLE
[Release 3.1] More crypto extensions

### ISSUE THREAD

**Issue by larryk85** [AntelopeIO/cdt#45]
To make the release of 3.0 in time we had to cut the scope of the crypto extension wrappers for C++.

This work should include wrappers and datatypes for 

`alt_bn128_*` functions to have more than just a basic C++ wrapper over those.  I.e. create a point data types to take as input and as results.

use std::vector of pairs for `alt_bn128_pair`

Create bigint datatype for `mod_exp`.

And the same kind of thing for `blake2_f` by using std::vectors and std::string, etc.

**Comment by smlu** [comment]
I suggest using `std::span` instead of `std::vector` for function args to make functions more generic. This way one could pass other byte containers to function (e.g. `std::array`) and avoid unnecessary copying/heap allocation which would be required otherwise to convert container's data to `std::vector`.
